config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  namespace :api, defaults: { format: :json } do
    resource :generator, only: :create
  end
  resources :text_sources
end

app/models/generator.rb
# Generator generate paragraphs from given text sources.
class Generator
  attr_accessor :text_source_ids, :paragraphs, :length

  def initialize(options = {})
    @text_source_ids = options.delete(:text_source_ids)
    @paragraphs = Integer(options.delete(:paragraphs) || 3)
    @length = Integer(options.delete(:length) || 6)
  end

  def generate
    Array.new(paragraphs).map { generate_paragraph(length) }.compact.join("\n\n")
  end

  private

  def generate_paragraph(num_sentence)
    num_sentence = [num_sentence + rand(3) - 1, 1].max
    Array.new(num_sentence).map { generate_sentence(6) }.compact.join(' ')
  end

  def generate_sentence(num_words)
    num_words = [num_words + rand(7) - 3, 2].max
    (words.sample(num_words) + [predicates.sample]).compact.join(' ')
  end

  def predicates
    @predicates ||= begin
      if text_source_ids
        TextSource.all_predicates.slice(*text_source_ids.map(&:to_i)).values.flatten
      else
        TextSource.all_predicates.values.flatten
      end
    end
  end

  def words
    @words ||= begin
      if text_source_ids
        TextSource.all_words.slice(*text_source_ids.map(&:to_i)).values.flatten
      else
        TextSource.all_words.values.flatten
      end
    end
  end
end

app/models/text_source.rb
# encoding: utf-8

# TextSource is dictionary for text generation.
class TextSource < ActiveRecord::Base
  after_save :flush_cache

  def self.all_predicates
    Rails.cache.fetch('predicates') do
      Hash[all.map { |ts| [ts.id, ts.predicates] }]
    end
  end

  def self.all_words
    Rails.cache.fetch('words') do
      Hash[all.map { |ts| [ts.id, ts.words] }]
    end
  end

  def stripped_content
    @stripped_content ||= content.gsub(/[^0-9가-힣.?,\s]/, '')
  end

  def words
    stripped_content.split.select { |w| w.match(/[.?!]$/).nil? }
  end

  def predicates
    stripped_content.split.select { |w| w.match(/[.?!]$/) }
  end

  def flush_cache
    Rails.cache.clear
  end
end

app/controllers/api/generators_controller.rb
# Api::GeneratorsController generates ipsum texts.
class Api::GeneratorsController < ApplicationController
  def create
    ipsum = Generator.new(
      text_source_ids: params[:text_source_ids],
      paragraphs: params[:paragraphs],
      length: paragraph_length
    ).generate

    render json: { ipsum: ipsum }
  end

  private

  def paragraph_length
    case params[:length]
    when 'long' then 10
    when 'medium' then 6
    when 'short' then 3
    else 6
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @text_sources = TextSource.select(:id, :title).all
  end
end

app/controllers/text_sources_controller.rb
class TextSourcesController < ApplicationController
  # GET /text_sources
  # GET /text_sources.json
  def index
    @text_sources = TextSource.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @text_sources }
    end
  end

  # GET /text_sources/1
  # GET /text_sources/1.json
  def show
    @text_source = TextSource.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @text_source }
    end
  end

  # GET /text_sources/new
  # GET /text_sources/new.json
  def new
    @text_source = TextSource.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @text_source }
    end
  end

  # GET /text_sources/1/edit
  def edit
    @text_source = TextSource.find(params[:id])
  end

  # POST /text_sources
  # POST /text_sources.json
  def create
    @text_source = TextSource.new(text_source_params)

    respond_to do |format|
      if @text_source.save
        format.html { redirect_to @text_source, notice: 'Text source was successfully created.' }
        format.json { render json: @text_source, status: :created, location: @text_source }
      else
        format.html { render action: "new" }
        format.json { render json: @text_source.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /text_sources/1
  # PUT /text_sources/1.json
  def update
    @text_source = TextSource.find(params[:id])

    respond_to do |format|
      if @text_source.update_attributes(text_source_params)
        format.html { redirect_to @text_source, notice: 'Text source was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @text_source.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /text_sources/1
  # DELETE /text_sources/1.json
  def destroy
    @text_source = TextSource.find(params[:id])
    @text_source.destroy

    respond_to do |format|
      format.html { redirect_to text_sources_url }
      format.json { head :ok }
    end
  end

  protected

  def text_source_params
    params.require(:text_source).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/text_sources_helper.rb
module TextSourcesHelper
end

app/views/home/_share_buttons.html.slim
.container
  .share_buttons
    .share_button.twitter
      a.twitter-share-button data-count="horizontal" data-lang="en" data-text="한글 버전의 Lorem Ipsum" data-url="http://hangul.thefron.me" data-via="thefron" href="https://twitter.com/share"  트윗하기
    .share_button.google
      .g-plusone data-href="http://hangul.thefron.me" data-size="medium"
    .share_button.facebook
      iframe src="https://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fhangul.thefron.me&layout=button_count&action=like&size=small&show_faces=false&share=false&appId=178809282203022" width="100px" height="21" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"
    script src="//platform.twitter.com/widgets.js" type="text/javascript"
    script src="//apis.google.com/js/platform.js" async=true defer=true
      | {lang: 'ko'}

app/views/home/index.html.slim
.container
  .row
    .column
      h1.page_title
        | 한글입숨
      p
        | 무의미한 한글 텍스트 생성기입니다.<br/>
        a href="http://www.lipsum.com/" target="_blank" 왜 사용하나요?
  .row
    .column
      = form_tag api_generator_path(format: 'json'), id: 'generate_ipsum', remote: true, method: :post do
        .row
          .column
            .row
              .column
                = label_tag 'paragraphs', '문단 수'
                = number_field_tag :paragraphs, 3, { in: 1..20 }
              .column
                = label_tag 'length', '문단 길이'
                = select_tag 'length', options_for_select([['길게', 'long'], ['중간', 'medium'], ['짧게', 'short']])
          .column
            .row
              .column
                = label_tag 'text_source_ids', '텍스트 소스'
                = select_tag 'text_source_ids[]', options_from_collection_for_select(@text_sources, "id", "title")
        .row
          .column
            = submit_tag '생성하기', class: 'button button-large button-outline'
  .row
    .column
      .ipsum_result_container
        .span12.well
          #ipsum_result

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title HangulIpsum
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  body
    .container
      = yield

app/views/layouts/home.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title 한글입숨
    meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0" name="viewport" /
    meta content=("한글입숨 - 무의미한 한글 텍스트 생성기") property="og:title" /
    meta content="website" property="og:type" /
    meta content="http://hangul.thefron.me" property="og:url" /
    meta content=image_url('apple-touch-icon.png') property="og:image" /
    meta content="한글입숨" property="og:site_name" /
    meta content="100000800851255" property="fb:admins" /
    meta content=("한글판 로렘입숨. 무의미한 한글 텍스트를 생성해 줍니다.") property="og:description" /
    meta content=("한글판 로렘입숨. 무의미한 한글 텍스트를 생성해 줍니다.") name="description" /
    meta content="한글, 로렘입숨, lorem ipsum, 한글입숨" name="keyword" /
    link href="http://hangul.thefron.me/" rel="canonical" /

    // Favicons
    link rel="apple-touch-icon" sizes="180x180" href=image_path('apple-touch-icon.png')
    link rel="icon" type="image/png" sizes="32x32" href=image_path('favicon-32x32.png')
    link rel="icon" type="image/png" sizes="16x16" href=image_path('favicon-16x16.png')
    link rel="manifest" href=asset_path('manifest.json')
    link rel="mask-icon" href=image_path('safari-pinned-tab.svg') color="#5bbad5"
    meta name="msapplication-TileColor" content="#9f00a7"
    meta name="msapplication-TileImage" content=image_path('mstile-150x150.png')
    meta name="theme-color" content="#ffffff"

    = stylesheet_link_tag    'home'
    = javascript_include_tag 'home'
    = csrf_meta_tags
  body
    = yield
    = render 'share_buttons'
    .container
      footer
        p
          | Powered by
          a href="http://thefron.me" rel="author" target="_blank"  Thefron
    script async=true src="https://www.googletagmanager.com/gtag/js?id=G-6CX7QXCD7F"
    javascript:
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'G-6CX7QXCD7F');

    script async=true src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"
    javascript:
      (adsbygoogle = window.adsbygoogle || []).push({
        google_ad_client: "ca-pub-3994473707684031",
        enable_page_level_ads: true
      });

app/views/text_sources/_form.html.erb
<%= form_for(@text_source) do |f| %>
  <% if @text_source.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@text_source.errors.count, "error") %> prohibited this text_source from being saved:</h2>

      <ul>
      <% @text_source.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/text_sources/edit.html.erb
<h1>Editing Text Source</h1>

<%= render 'form' %>

<%= link_to 'Show', @text_source %> |
<%= link_to 'Back', text_sources_path %>

app/views/text_sources/index.html.erb
<h1>Listing Text Sources</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @text_sources.each do |text_source| %>
  <tr>
    <td><%= truncate text_source.title %></td>
    <td><%= truncate text_source.content %></td>
    <td><%= link_to 'Show', text_source %></td>
    <td><%= link_to 'Edit', edit_text_source_path(text_source) %></td>
    <td><%= link_to 'Destroy', text_source, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Text source', new_text_source_path %>

app/views/text_sources/new.html.erb
<h1>New Text Source</h1>

<%= render 'form' %>

<%= link_to 'Back', text_sources_path %>

app/views/text_sources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @text_source.title %>
</p>

<p>
  <b>Content:</b>
  <%= @text_source.content %>
</p>


<%= link_to 'Edit', edit_text_source_path(@text_source) %> |
<%= link_to 'Back', text_sources_path %>